# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        MainWindow.setStyleSheet("background-color:rgb(25,35,45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 129, 1181, 721))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setGeometry(QtCore.QRect(1006, 0, 181, 41))
        self.imgLabel.setAutoFillBackground(False)
        self.imgLabel.setStyleSheet("QLabel{border-image:url(\"C:/Users/javen/Desktop/高清Logo/白色条形.png\");}")
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.netCardLabel = QtWidgets.QLabel(self.centralwidget)
        self.netCardLabel.setGeometry(QtCore.QRect(520, 0, 471, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.netCardLabel.setFont(font)
        self.netCardLabel.setStyleSheet("color:white;\n"
"font-family:宋体;\n"
"/*字体大小为20点*/\n"
"font-size:10pt;")
        self.netCardLabel.setObjectName("netCardLabel")
        self.BADButton = QtWidgets.QPushButton(self.centralwidget)
        self.BADButton.setGeometry(QtCore.QRect(465, 80, 81, 29))
        self.BADButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#ed1941;\n"
"    /*边框圆角半径为8像素*/ \n"
"    border:3px solid black;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#d71345;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#d71345;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.BADButton.setObjectName("BADButton")
        self.UDPButton = QtWidgets.QPushButton(self.centralwidget)
        self.UDPButton.setGeometry(QtCore.QRect(99, 80, 81, 29))
        self.UDPButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(80,95,105);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border:3px solid rgb(0,0,0);\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.UDPButton.setObjectName("UDPButton")
        self.OTHERButton = QtWidgets.QPushButton(self.centralwidget)
        self.OTHERButton.setGeometry(QtCore.QRect(373, 80, 82, 29))
        self.OTHERButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(80,95,105);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border:3px solid rgb(0,0,0);\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.OTHERButton.setObjectName("OTHERButton")
        self.TCPButton = QtWidgets.QPushButton(self.centralwidget)
        self.TCPButton.setGeometry(QtCore.QRect(7, 80, 82, 29))
        self.TCPButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(80,95,105);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border:3px solid rgb(0,0,0);\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.TCPButton.setObjectName("TCPButton")
        self.ARPButton = QtWidgets.QPushButton(self.centralwidget)
        self.ARPButton.setGeometry(QtCore.QRect(282, 80, 81, 29))
        self.ARPButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(80,95,105);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border:3px solid rgb(0,0,0);\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.ARPButton.setObjectName("ARPButton")
        self.ICMPButton = QtWidgets.QPushButton(self.centralwidget)
        self.ICMPButton.setGeometry(QtCore.QRect(190, 80, 82, 29))
        self.ICMPButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(80,95,105);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border:3px solid rgb(0,0,0);\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,59,65);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.ICMPButton.setObjectName("ICMPButton")
        self.chooseNetCard = QtWidgets.QPushButton(self.centralwidget)
        self.chooseNetCard.setGeometry(QtCore.QRect(-2, 0, 102, 32))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.chooseNetCard.setFont(font)
        self.chooseNetCard.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#f3704b;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.chooseNetCard.setObjectName("chooseNetCard")
        self.fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileButton.setGeometry(QtCore.QRect(305, 0, 102, 32))
        self.fileButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(142,133,112);\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(122,113,92);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(122,113,92);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.fileButton.setObjectName("fileButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(203, 0, 102, 32))
        self.clearButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(80,95,105);\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,65,75);\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:rgb(50,65,75);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.clearButton.setObjectName("clearButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(100, 0, 103, 32))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#101010;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#130c0e;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#130c0e;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素 \n"
"    padding-left:3px;\n"
"    padding-right:3px;*/ \n"
"    /*上内边距为3像素，让按下时字向下移动3像素  \n"
"    padding-top:3px;*/\n"
"}\n"
"")
        self.stopButton.setObjectName("stopButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1010, 80, 181, 31))
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:red;")
        self.label_2.setObjectName("label_2")
        self.rlabel = QtWidgets.QLabel(self.centralwidget)
        self.rlabel.setGeometry(QtCore.QRect(690, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rlabel.setFont(font)
        self.rlabel.setStyleSheet("")
        self.rlabel.setText("")
        self.rlabel.setObjectName("rlabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:red;")
        self.label_3.setObjectName("label_3")
        self.rlabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.rlabel_2.setGeometry(QtCore.QRect(900, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rlabel_2.setFont(font)
        self.rlabel_2.setStyleSheet("")
        self.rlabel_2.setText("")
        self.rlabel_2.setObjectName("rlabel_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.netCardLabel.setText(_translate("MainWindow", "当前选择网卡：                    "))
        self.BADButton.setText(_translate("MainWindow", "恶意包"))
        self.UDPButton.setText(_translate("MainWindow", "UDP"))
        self.OTHERButton.setText(_translate("MainWindow", "其他"))
        self.TCPButton.setText(_translate("MainWindow", "TCP"))
        self.ARPButton.setText(_translate("MainWindow", "ARP"))
        self.ICMPButton.setText(_translate("MainWindow", "ICMP"))
        self.chooseNetCard.setText(_translate("MainWindow", "开始"))
        self.fileButton.setText(_translate("MainWindow", "选择文件"))
        self.clearButton.setText(_translate("MainWindow", "清空记录"))
        self.stopButton.setText(_translate("MainWindow", "暂停"))
        self.label.setText(_translate("MainWindow", "注：双击可查看详细信息"))
        self.label_2.setText(_translate("MainWindow", "瞬时恶性包率："))
        self.label_3.setText(_translate("MainWindow", "总恶性包率："))
