# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Net_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1188, 883)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(1, -9, 1181, 891))
        self.tableWidget.setStyleSheet("/*表格的一种美化方式*/\n"
"\n"
"\n"
"    QHeaderView::section\n"
"{\n"
"    font-size:20px;\n"
"    font-family:\"Microsoft YaHei\";\n"
"    text-align:left;\n"
"    min-height:49px;\n"
"    max-height:49px;\n"
"    margin-left:0px;\n"
"    padding-left:0px;\n"
"    border:1px solid #130c0e ;\n"
"    font:Bold;\n"
"    color:white;\n"
"    background-color:rgb(20,100,160);\n"
"\n"
"}/*\n"
"QBrush\n"
"{\n"
"color:red;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    font-size:20px;\n"
"    font-family:\"Microsoft YaHei\";\n"
"    color:#FFFFFF;\n"
"    text-align:left;\n"
"    min-height:49px;\n"
"    max-height:49px;\n"
"    margin-left:0px;\n"
"    padding-left:0px;\n"
"}*/\n"
"\n"
"/*background:#FFFFFF;\n"
"QTableWidget\n"
"{\n"
"    border:none;\n"
"    font-size:20px;\n"
"    font-family:\"Microsoft YaHei\";\n"
"    color:rgb(25,35,45);\n"
"}\n"
"\n"
"\n"
"QTableWidget::item\n"
"{\n"
"    border-bottom:1px solid #EEF1F7 ;\n"
"    color:rgb(25,35,45);\n"
"}*/\n"
"/*\n"
"QTableWidget::item::selected\n"
"{\n"
"    color:#45b97c;\n"
"}\n"
"*/\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background: rgba(255,255,255,20%);\n"
"    border: 0px solid grey;\n"
"    border-radius:3px;\n"
"    width: 8px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background:rgba(255,255,255,10%);\n"
"}\n"
"\n"
"\n"
"QScollBar::add-line:vertical, QScrollBar::sub-line:vertical\n"
"{\n"
"    background:transparent;\n"
"}\n"
"")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.tableWidget.setColumnWidth(0, 100)
        for i in range(6):
            self.tableWidget.setColumnWidth(1+i, 179)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "捕获时间"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "源地址"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "目标地址"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "长度"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "协议类型"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "是否恶意"))
